/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class AdminMahasiswa extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    /**
     * Creates new form AdminMahasiswa
     */
    public AdminMahasiswa() {
        initComponents();
        setTitle("TABLE DATA MAHASISWA");
        koneksi ();
        tabel ();
        tabel.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabelLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        mahasiswa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        NavMenuUtama = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        mahasiwa = new javax.swing.JMenuItem();
        kembali = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        tabelLabel.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        tabelLabel.setForeground(new java.awt.Color(255, 255, 255));
        tabelLabel.setText("TABEL MAHASIWA");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NISN", "Nama", "Jenis Kelamin", "Agama", "Alamat", "No Telepon", "Asal Sekolah", "Rata Rata Nilai", "Nama Orang Tua/Wali", "No Telepon Orang Tua/Wali"
            }
        ));
        tabel.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabel);

        mahasiswa.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        mahasiswa.setText("PILIH MAHASISWA");
        mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabelLabel)
                .addGap(506, 506, 506))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tabelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);

        NavMenuUtama.setText("Menu Utama");

        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        NavMenuUtama.add(admin);

        mahasiwa.setText("Mahasiwa");
        mahasiwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiwaMouseClicked(evt);
            }
        });
        mahasiwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiwaActionPerformed(evt);
            }
        });
        NavMenuUtama.add(mahasiwa);

        jMenuBar1.add(NavMenuUtama);

        kembali.setText("Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jMenuBar1.add(kembali);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koneksi (){
        try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost:8111/pbo_db", "root", "");
         stat=con.createStatement();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}
    }
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("NISN");
        t.addColumn("Nama");
        t.addColumn("Jenis Kelamin");
        t.addColumn("Agama");
        t.addColumn("Alamat");
        t.addColumn("No Telepon");
        t.addColumn("Asal Sekolah");
        t.addColumn("Rata Rata Nilai");
        t.addColumn("Nama Orang Tua/Wali");
        t.addColumn("No Telepon Orang Tua/Wali");
        tabel.setModel(t); 
        try{ res= stat.executeQuery("SELECT * FROM mahasiswa");
            while (res.next()) {
                t.addRow(new Object[]{ res.getString("NISN"),
                res.getString("Nama"),
                res.getString("Jenis Kelamin"),
                res.getString("Agama"),
                res.getString("Alamat"),
                res.getString("No Telepon"),
                res.getString("Asal Sekolah"),
                res.getString("Rata Rata Nilai"),
                res.getString("Nama Orang Tua/Wali"),
                res.getString("No Telepon Orang Tua/Wali")
                });
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }    
    }
    
    ControlMahasiswa data = new  ControlMahasiswa();
    private void mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaActionPerformed
        // TODO add your handling code here:
        int index = tabel.getSelectedRow();
        
        TableModel model = tabel.getModel();
        
        String nisn = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String jk = model.getValueAt(index, 2).toString();
        String agama = model.getValueAt(index, 3).toString();
        String alamat = model.getValueAt(index, 4).toString();
        String notelp = model.getValueAt(index, 5).toString();
        String aslsklh = model.getValueAt(index, 6).toString();
        String rata = model.getValueAt(index, 7).toString();
        String namaOr = model.getValueAt(index, 8).toString();
        String notelpOr = model.getValueAt(index, 9).toString();
        
        data.setVisible(true);
        data.pack();
        data.setLocationRelativeTo(null);
        data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        data.nisn.setText(nisn);
        data.nama.setText(nama);
        data.jk.setSelectedItem(jk);
        data.agama.setText(agama);
        data.alamat.setText(alamat);
        data.notelp.setText(notelp);
        data.aslsklh.setText(aslsklh);
        data.rata.setText(rata);
        data.namaOr.setText(namaOr);
        data.notelpOr.setText(notelpOr);
        dispose();
    }//GEN-LAST:event_mahasiswaActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void mahasiwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiwaActionPerformed
        // TODO add your handling code here:
        //new ControlMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_mahasiwaActionPerformed

    private void mahasiwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiwaMouseClicked
        // TODO add your handling code here:
        new ControlMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_mahasiwaMouseClicked

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        new AdminLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu NavMenuUtama;
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu kembali;
    private javax.swing.JButton mahasiswa;
    private javax.swing.JMenuItem mahasiwa;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tabelLabel;
    // End of variables declaration//GEN-END:variables
}
